### ISSUE TITLE
minigun turret bugged

### ISSUE THREAD

**Issue by randyrandoms** [sumghai/DefensiveMachineGunTurretPack#8]
**Describe the bug:**  
 combat extended is active and when used the m137 minigun auto turrets mag randomly cooks off in a spiral motion cooks off up to 1000 rounds of its mag at a time in all directions every 1/2 burst of fire that killed 2 of my pawns even when it hasn't been damaged

**Expected behavior:**  
 I expected the turret to turn raiders into swiss cheese not spraying bullets in random directions killing my pawns

**Steps to reproduce:**  

1. place the turret
2. spawn target for it to shoot does not happen every time it shoots but frequently happens
3. 

**Additional information:**

## System and Game Configuration
**Operating System:** Windows 11 (no build number specified)
**Physical RAM:** 32gb
**RimWorld base game version:** 1.4.3614
**RimWorld DLCs loaded:** Royalty, Ideology, Biotech
**DMGTP mod version:** 1.8.2
**DMGTP mod downloaded from:** Steam
**Your mod list:**  (User did not follow instructions to narrow down modlist)

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, DMGTP, and its dependencies
- [x] I am NOT running any mods with known incompatibilities with DMGTP
- [ ] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [ ] I have confirmed that the issue does not happen if DMGTP is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

![20230124191512_1](https://user-images.githubusercontent.com/82009955/214465735-4784469c-2c12-4c7d-b22b-1cb613db3a4d.jpg)

![20230124191519_1](https://user-images.githubusercontent.com/82009955/214465754-04c18f4f-49cd-4c9c-ad6d-23541c15d9d1.jpg)

![20230124191526_1](https://user-images.githubusercontent.com/82009955/214465781-d611cfe6-df3e-4759-bc0b-5123662fb643.jpg

the attached images are my active mod list all of them except researcher pall 1.3 is 1.4

(EDITED by @sumghai with updated info)

**Comment by sumghai** [comment]
Please fix the following problems with your bug report:

- Missing Operating System version and build number
- Missing RimWorld version and build number (e.g. 1.4.xxxx, as shown on the main menu)
- Check your DMGTP mod version; v1.4 was released _all the way back in Jan 2019_ and was meant for RW 1.0
- Did you download the mod from Steam or GitHub?
- Why is your Combat Extended shown as red in your modlist? Make sure you're not running the outdated RW 1.3 version that's still on Steam
- Narrow down your modlist to only Harmony, Core, Combat Extended and DMGTP

**Comment by randyrandoms** [comment]
1.4.3614

Windows 11 most recent version

DMGTP was downloaded from steam version v1.8.2

combat extended is red due to me using rimthreaded

after disabling all other mods apart from combat extended bug still occurs

**Comment by sumghai** [comment]
Alright, I reproduced the behavior with the following mods:
- RimWorld 1.4.3613 rev641
- Harmony v2.2.2.0
- Combat Extended v1.4.5.1
- DMGTP v1.8.2

The turret is not actually cooking off, as the little "flame" in the middle of the turret is actually the muzzle flash (RimWorld does not account for barrel length, and just renders the muzzle flash mote in the center of the weapon).

As for the M134 Sentry gun spinning wildly while firing, what is happening is that the turret has a very high `burstShotCount` of `300` and `aimedBurstShotCount` of `150`, and the turret tries to fire a full burst at its current target - if the target is downed before the burst shot is fully finished, the turret spins wildly looking for an alternative target.

I believe this is actually an edge case behavior within the Combat Extended mod itself, because when I modified one of CE's own turrets with a high firing rate and high ammo capacity, this exact spinning-wildly-while-tracking-new-targets also occurred.

I could drastically reduce the rate of fire on the minigun turret to something like `50` `burstShotCount` and `25` `aimedBurstShotCount`, but I suspect this would heavily nerf the ability for the M134 Sentry gun to deal with mechanoids. Alternative, CE itself may need to be patched to stop firing if the target is downed halfway through a burst shot.

I'll have a chat with the CE team and see what they think.

**Comment by sumghai** [comment]
Turns out this is indeed a CE bug, and it has very little to do with burst shot counts - if a target is downed during failing, retargeting sometimes fails and the spinning-wildly effect is actually recoil causing the weapon to fire upwards.

The CE team is already working on a fix, so you'll just have to wait until then:

CombatExtended-Continued/CombatExtended/pull/2285

In summary: Not a bug with DMGTP.
